[pytest]
minversion = 7.0
addopts = -v -s --tb=short --alluredir=allure-results --clean-alluredir
testpaths = tests
pythonpath = src

# Маркеры для разделения типов тестов
markers =
    backend: Backend тесты (MongoDB)
    web: Web тесты (Playwright)
    mobile: Mobile тесты (Appium)
    smoke: Smoke тесты
    regression: Regression тесты